# Generated by Django 4.0 on 2022-12-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.user')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='target', to='core.user')),
            ],
        ),
        migrations.DeleteModel(
            name='logins',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
